import { PROJECT_DEFAULTS, REPORT_DEFAULTS } from './report-defaults.js';

// Working scenarios, not findings or legal classifications. No case records are created.
export const FRAUD_PRESETS = [
  {id:'marketplace',name:'Zakup na portalu ogłoszeniowym',focus:'oferty, uzgodnionych warunków i realizacji zakupu',questions:['Czy oferta i korespondencja dotyczą tej samej rzeczy i osoby?','Co uzgodniono w sprawie ceny, płatności i dostawy?','Czy brak dostawy wynika z okoliczności wskazanych przez sprzedawcę?'],materials:['oferta i identyfikator konta','pełna korespondencja','potwierdzenie zapłaty i status przesyłki'],identifiers:'konto sprzedawcy, numer oferty, telefon, rachunek, numer przesyłki',alternative:'opóźnienie dostawy, spór co do umowy lub przejęcie konta sprzedawcy'},
  {id:'fake-shop',name:'Fałszywy sklep internetowy',focus:'wiarygodności sklepu oraz losu zamówienia i płatności',questions:['Jak sklep przedstawiał sprzedawcę i warunki transakcji?','Czy dane rejestrowe odpowiadają operatorowi strony?','Dokąd skierowano płatność i czy zamówienie zrealizowano?'],materials:['kopia strony, regulaminu i zamówienia','potwierdzenie płatności','korespondencja i dane rejestrowe z datą sprawdzenia'],identifiers:'domena, dane sprzedawcy, rachunek, identyfikator zamówienia',alternative:'rzeczywisty sprzedawca z problemami realizacyjnymi lub podszycie pod istniejącą firmę'},
  {id:'blik',name:'Wyłudzenie płatności BLIK',focus:'prośby o kod lub zatwierdzenie płatności i jej rzeczywistego przeznaczenia',questions:['Kto i jak zwrócił się o wykonanie płatności?','Co wyświetlono przy zatwierdzaniu transakcji?','Czy konto nadawcy mogło być przejęte?'],materials:['wiadomości z prośbą o płatność','potwierdzenie transakcji i jej czasu','opis ekranów autoryzacji i kontakt z właścicielem konta'],identifiers:'konto komunikatora, numer transakcji, czas, odbiorca lub punkt realizacji',alternative:'rzeczywista prośba znajomego albo przejęcie jego konta; nie utożsamiaj konta z osobą piszącą'},
  {id:'bank-call',name:'Podszycie pod pracownika banku',focus:'rozmowy i dyspozycji przedstawianych jako zabezpieczenie środków',questions:['Jak rozmówca uzasadniał kontakt i żądane czynności?','Czy polecał przelew, wypłatę lub instalację aplikacji?','Czy bank potwierdza taki kontakt w swoich zapisach?'],materials:['historia połączeń i dostępne nagrania','wiadomości oraz instrukcje rozmówcy','wyciąg, potwierdzenia dyspozycji i informacje z banku'],identifiers:'prezentowany numer, rachunki, czasy dyspozycji, nazwa aplikacji',alternative:'legalny kontakt banku; prezentowany numer nie dowodzi tożsamości rozmówcy'},
  {id:'parcel',name:'Dopłata do przesyłki',focus:'wiadomości o przesyłce i strony żądającej dopłaty',questions:['Czy odbiorca oczekiwał przesyłki i czy numer jest zgodny?','Do jakiej domeny prowadził link?','Jakie dane lub płatności zostały przekazane?'],materials:['oryginalna wiadomość z datą','adres i kopia strony','informacje przewoźnika i transakcje po zdarzeniu'],identifiers:'nadawca wiadomości, domena, numer przesyłki, rachunek lub transakcja',alternative:'prawdziwa dopłata przewoźnika; podobieństwo strony nie potwierdza jej pochodzenia'},
  {id:'utility',name:'Fałszywa zaległość za media lub usługę',focus:'wezwania do zapłaty i deklarowanej zaległości',questions:['Czy zobowiązanie istnieje u wskazanego usługodawcy?','Czy numer klienta i kwota odpowiadają rozliczeniom?','Gdzie prowadził link i komu zapłacono?'],materials:['wezwanie lub SMS','rzeczywiste rozliczenia usługodawcy','kopia strony płatności i potwierdzenie przelewu'],identifiers:'numer klienta, identyfikator wezwania, domena, rachunek',alternative:'autentyczne wezwanie, pomyłka rozliczeniowa lub podszycie'},
  {id:'seller-link',name:'Fałszywy kupujący i link do odbioru pieniędzy',focus:'kontaktu z kupującym i czynności rzekomo potrzebnych do otrzymania zapłaty',questions:['Czy kontakt przeniesiono poza portal?','Jakich danych zażądano na stronie odbioru zapłaty?','Czy zamiast wpływu środków nastąpiło obciążenie?'],materials:['oferta i rozmowa z kupującym','link oraz kopia formularza','transakcje i komunikaty autoryzacyjne'],identifiers:'konto kupującego, telefon, domena, transakcje',alternative:'prawidłowa procedura platformy lub zewnętrzna strona podszywająca się pod nią'},
  {id:'investment',name:'Fałszywa inwestycja',focus:'oferty inwestycyjnej, wpłat i możliwości odzyskania środków',questions:['Jakie zyski i ryzyka przedstawiono?','Czy widoczne saldo ma potwierdzenie poza panelem?','Jak uzasadniano odmowę wypłaty i dodatkowe opłaty?'],materials:['reklama i oferta','historia kontaktu i wpłat','żądania wypłaty, odpowiedzi i dokumenty podmiotu'],identifiers:'marka, domena, konsultanci, rachunki i numery transakcji',alternative:'strata inwestycyjna lub spór z rzeczywistym podmiotem; panel nie jest samodzielnym dowodem posiadania aktywów'},
  {id:'crypto',name:'Inwestycja w kryptowaluty',focus:'oferty i przepływów aktywów cyfrowych',questions:['W jakiej sieci i w jakim aktywie dokonano wpłat?','Czy identyfikatory transakcji potwierdzają deklarowane transfery?','Co łączy adres odbiorczy z podmiotem oferującym inwestycję?'],materials:['oferta i rozmowy','potwierdzenia giełdy lub portfela','identyfikatory transakcji i stan danych sieciowych z datą'],identifiers:'sieć, aktywo, adresy, hash transakcji, domena platformy',alternative:'błąd sieci, adresu lub spór inwestycyjny; adres nie identyfikuje sam w sobie osoby'},
  {id:'romance',name:'Oszustwo matrymonialne lub romantyczne',focus:'rozwoju relacji i próśb o przekazanie pieniędzy',questions:['Jak nawiązano kontakt i przedstawiono tożsamość?','Jakie zdarzenia uzasadniały prośby finansowe?','Czy opisy, zdjęcia i dane pozostają spójne w czasie?'],materials:['pełna historia kontaktu','profile i przekazane dokumenty','potwierdzenia wpłat oraz uzasadnienia żądań'],identifiers:'profile, aliasy, telefony, adresy poczty i odbiorcy płatności',alternative:'autentyczna relacja lub wykorzystanie cudzej tożsamości; sam brak spotkania nie rozstrzyga sprawy'},
  {id:'family',name:'Podszycie pod członka rodziny',focus:'wiadomości o nowym numerze lub nagłej potrzebie finansowej',questions:['Jak wyjaśniono zmianę numeru lub niemożność rozmowy?','Czy tożsamość potwierdzono niezależnym kanałem?','Jak wskazano odbiorcę i cel przelewu?'],materials:['SMS-y i rozmowy komunikatora','historia połączeń','potwierdzenia płatności i relacja właściwej osoby'],identifiers:'nowy i wcześniejszy numer, profil, rachunek, czas kontaktu',alternative:'rzeczywista prośba krewnego lub podszycie; zapisany opis kontaktu nie potwierdza nadawcy'},
  {id:'authority',name:'Podszycie pod instytucję lub osobę zaufania',focus:'deklarowanej roli rozmówcy i żądania przekazania środków',questions:['Jaką funkcję deklarował rozmówca i co nakazywał?','Czy żądano zachowania tajemnicy lub pilnego działania?','Czy wskazana instytucja potwierdza kontakt?'],materials:['wiadomości i dostępne nagrania','przekazane dokumenty','opis przekazania pieniędzy i niezależna weryfikacja kontaktu'],identifiers:'deklarowane dane, numery, rachunki, miejsca i czasy przekazania',alternative:'autentyczny kontakt albo podszycie; deklarowana funkcja wymaga niezależnego potwierdzenia'},
  {id:'ceo',name:'Podszycie pod przełożonego — BEC / CEO',focus:'dyspozycji finansowej przypisywanej przełożonemu',questions:['Czy dyspozycja odbiegała od normalnej procedury?','Czy pochodziła z przejętej skrzynki czy podobnego adresu?','Jak i przez kogo ją zweryfikowano?'],materials:['wiadomości z pełnymi nagłówkami','dyspozycja, akceptacje i procedura płatnicza','potwierdzenia przelewów i dostępne logi poczty'],identifiers:'adres nadawcy i Reply-To, domena, Message-ID, rachunek',alternative:'uprawniona dyspozycja, błąd pracownika lub kompromitacja konta'},
  {id:'invoice',name:'Podmiana rachunku na fakturze',focus:'zmiany danych płatniczych i przebiegu obiegu dokumentu',questions:['Która wersja faktury zawierała inny rachunek?','W którym etapie obiegu pojawiła się zmiana?','Czy kontrahent potwierdził zmianę niezależnym kanałem?'],materials:['wszystkie dostępne wersje faktury','oryginalne wiadomości i załączniki','potwierdzenie płatności i uzgodnienia z kontrahentem'],identifiers:'numery faktur, rachunki, skróty plików, Message-ID',alternative:'prawidłowa zmiana rachunku lub błąd księgowy; różnica plików nie identyfikuje autora zmiany'},
  {id:'job',name:'Fałszywa oferta pracy',focus:'rekrutacji i żądań pieniędzy, danych lub wykonywania przelewów',questions:['Czy pracodawca potwierdza ofertę i rekrutera?','Jakie opłaty lub dokumenty miały warunkować zatrudnienie?','Czy polecano odbierać lub przekazywać cudze środki?'],materials:['ogłoszenie i rozmowy','umowy, formularze i instrukcje','wpłaty oraz weryfikacja danych pracodawcy'],identifiers:'ogłoszenie, rekruter, domena, rachunki, nazwa pracodawcy',alternative:'rzeczywista rekrutacja lub podszycie; dane istniejącej firmy nie przesądzają o jej udziale'},
  {id:'tasks',name:'Płatne zadania i prowizje online',focus:'systemu zadań, obietnic prowizji i dopłat wymaganych do wypłaty',questions:['Czy początkowe wypłaty poprzedzały żądanie większych wpłat?','Jak wyliczano saldo i prowizje?','Co miało warunkować odblokowanie środków?'],materials:['instrukcje zadań i grupy komunikatora','historia salda oraz wpłat i wypłat','żądania dopłat i odpowiedzi na reklamację'],identifiers:'platforma, konta opiekunów, numery zadań, rachunki lub portfele',alternative:'spór o wynagrodzenie lub fikcyjne saldo; oddziel rzeczywiste wpływy od liczb w aplikacji'},
  {id:'rental',name:'Fałszywy wynajem mieszkania lub noclegu',focus:'oferty lokalu i wpłat rezerwacyjnych',questions:['Czy lokal istnieje i czy oferujący ma podstawę do jego wynajęcia?','Jak uzasadniano wpłatę przed oględzinami?','Czy rezerwacja lub umowa została zrealizowana?'],materials:['ogłoszenie, zdjęcia i adres','korespondencja oraz umowa','potwierdzenia zaliczki i weryfikacja lokalu'],identifiers:'adres, numer oferty, konto wynajmującego, rachunek',alternative:'spór umowny, anulowanie rezerwacji lub wykorzystanie cudzej oferty'},
  {id:'loan',name:'Pożyczka lub kredyt z opłatą wstępną',focus:'oferty finansowania i opłat poprzedzających wypłatę',questions:['Jakie warunki wypłaty środków przedstawiono?','Czy kolejne opłaty miały kończyć proces?','Czy podmiot i pośrednik potwierdzają udział w ofercie?'],materials:['oferta, umowa i harmonogram opłat','korespondencja','potwierdzenia wpłat i weryfikacja podmiotu'],identifiers:'pożyczkodawca, pośrednik, numer umowy, domena, rachunek',alternative:'rzeczywisty koszt usługi lub odmowa finansowania; samo niewypłacenie środków nie przesądza mechanizmu'},
  {id:'identity',name:'Wyłudzenie z wykorzystaniem cudzej tożsamości',focus:'użycia danych osoby do zawarcia umowy lub uzyskania świadczenia',questions:['Jakie dane wykorzystano i skąd mogły pochodzić?','Jak przebiegała weryfikacja i autoryzacja umowy?','Kto faktycznie otrzymał środki lub przedmiot umowy?'],materials:['wniosek, umowa i dokumentacja weryfikacji','dostępne logi autoryzacji i doręczeń','dyspozycje płatnicze i relacja właściciela danych'],identifiers:'numer umowy, dane użyte we wniosku, telefon, e-mail, rachunek, adres doręczenia',alternative:'upoważnienie, błąd danych lub nieuprawnione użycie; formalna tożsamość strony nie dowodzi wykonania czynności'},
  {id:'recovery',name:'Fałszywe odzyskiwanie utraconych środków',focus:'oferty odzyskania pieniędzy i opłat za jej realizację',questions:['Skąd oferent wiedział o wcześniejszej stracie?','Jakie dowody skuteczności i uprawnień przedstawił?','Czy odzyskanie środków uzależniono od kolejnej wpłaty?'],materials:['oferta i pełna korespondencja','rzekome potwierdzenia odzyskania','umowa, opłaty i odniesienie do wcześniejszej sprawy'],identifiers:'oferent, domena, rachunki, portfele i powiązania z poprzednim kontaktem',alternative:'rzeczywista usługa lub ponowne wyłudzenie; obietnica odzyskania nie stanowi potwierdzenia skuteczności'},
];

export function presetContent(id) {
  const x=FRAUD_PRESETS.find(p=>p.id===id);
  if(!x) throw new Error('Nieznany preset.');
  const project={...PROJECT_DEFAULTS,
    goal:`Celem raportu jest odtworzenie i ocena ${x.focus}. Należy ustalić przebieg kontaktu, treść zapewnień, wykonane dyspozycje i możliwe skutki majątkowe. Scenariusz roboczy: ${x.name}. Jego wybór nie przesądza ustaleń.`,
    questions:x.questions.map((q,i)=>`${i+1}. ${q}\n[Odpowiedź i podstawa źródłowa]`).join('\n'),
    scope:`Okres: [od–do]. Osoby i zdarzenia: [wskaż]. Analizie podlegają: ${x.materials.join('; ')}.\nPoza zakresem: [wskaż]. Kwoty wpłat, zwrotów i straty należy rozliczyć osobno dla każdej waluty.`,
  };
  const report={...REPORT_DEFAULTS,
    summary:`Scenariusz roboczy: ${x.name}.\nKontakt rozpoczął się [data i kanał]. Przedstawiono [treść oferty lub żądania]. Wykonano [czynności / płatności].\nWpłaty: [kwota i waluta]. Zwroty: [kwota i waluta]. Udokumentowany skutek: [wyliczenie i podstawa].\nNajważniejsze ustalenia: [identyfikatory]. Kwestie nierozstrzygnięte: [wskaż].`,
    method:REPORT_DEFAULTS.method+`\nDla tego scenariusza zestaw treść zapewnień z dokumentami oraz rzeczywistymi płatnościami. Materiały do porównania: ${x.materials.join('; ')}.`,
    entitiesIntro:`Identyfikatory wymagające zestawienia: ${x.identifiers}.\nDla każdego wskaż pochodzenie i datę pozyskania. Odróżnij dane deklarowane od zweryfikowanych oraz właściciela konta od osoby faktycznie korzystającej.\n[Uzupełnij podstawy identyfikacji i zastrzeżenia.]`,
    findingsIntro:`Dla każdego ustalenia porównaj zapewnienie lub żądanie z zaobserwowanym działaniem i skutkiem. Podaj źródła za i przeciw, poziom pewności oraz ograniczenia.\nPunkty do wyjaśnienia:\n${x.questions.map(q=>'• '+q).join('\n')}`,
    relationsIntro:`Sprawdź powiązania pomiędzy następującymi danymi: ${x.identifiers}.\n[Opisz podstawy każdej relacji, okres i pewność. Wspólny usługodawca lub podobny identyfikator nie oznacza wspólnego użytkownika.]`,
    chronologyIntro:`Zestaw kolejno: pierwszy kontakt → zapewnienia i instrukcje → czynności użytkownika → płatności → próby realizacji lub odzyskania środków.\n[Podaj daty, strefy, identyfikatory materiałów oraz rozbieżności między datą zdarzenia a datą zapisu.]`,
    hypothesesIntro:`Hipoteza robocza: [opisz możliwy mechanizm dla scenariusza „${x.name}”].\nDo rozważenia także: ${x.alternative}.\n[Wskaż argumenty za i przeciw każdemu wyjaśnieniu oraz materiał, który mógłby je rozstrzygnąć.]`,
    conclusions:`[Odpowiedz kolejno na pytania z części 01, odwołując się do identyfikatorów ustaleń.]\nZakres potwierdzonego przebiegu: [opisz].\nUdokumentowane wpłaty i zwroty: [zestaw osobno dla każdej waluty].\nKwestie bez rozstrzygnięcia: [wskaż]. Sam wybór scenariusza nie stanowi oceny odpowiedzialności.`,
    nextSteps:x.materials.map((m,i)=>`${i+1}. Sprawdzić kompletność i pochodzenie: ${m}. [Status i cel czynności]`).join('\n')+'\n[Dostosuj listę do dostępnych materiałów i zakresu sprawy.]',
    sourcesIntro:`Źródła istotne dla scenariusza: ${x.materials.join('; ')}.\n[W rejestrze wskaż autora, lokalizację, datę dostępu, niezależność i ograniczenia. Porównaj deklaracje oferenta z informacjami uzyskanymi niezależnie.]`,
    materialsIntro:`Lista materiałów do rozważenia:\n${x.materials.map(m=>'• '+m+' — [identyfikator / brak / nie dotyczy]').join('\n')}\n[Odnotuj pochodzenie, czas pozyskania, nazwę pliku i SHA-256. Dane dostępowe i aktywne kody nie powinny trafiać do opisu raportu.]`,
    preset:id,
  };
  return {project,report};
}

export function applyFraudPreset(p,id) {
  const next=presetContent(id), previous=FRAUD_PRESETS.some(x=>x.id===p.report.preset)?presetContent(p.report.preset):null;
  let changed=0, preserved=0;
  for(const [target,defaults,values,old] of [[p,PROJECT_DEFAULTS,next.project,previous?.project],[p.report,REPORT_DEFAULTS,next.report,previous?.report]]) {
    for(const [key,value] of Object.entries(values)) {
      if(key==='preset') continue;
      if(!String(target[key]??'').trim() || target[key]===defaults[key] || target[key]===old?.[key]) { target[key]=value; changed++; }
      else preserved++;
    }
  }
  p.report.preset=id;
  // Keep the optional custom chapter and all factual registers unchanged.
  return {changed,preserved};
}
